# Imagem base
FROM python:3.9-slim

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependência e instala o Flask
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código do servidor
COPY server.py .

# A porta que o container vai expor internamente (8080)
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["python", "server.py"]